dcf/dcf/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include   
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.decorators.cache import cache_page, never_cache

from dcf import views, feeds, sitemap
from django.conf.urls.i18n import i18n_patterns
app_name = "pinax_announcements"

# urlpatterns = [
#     url(r'^$', views.SectionListView.as_view(), name='index'),
#     url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
#     url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),
#     url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
#     url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),
#     url(r'^search/', views.SearchView.as_view(), name='search'),
#     url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),
#     url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
#     url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),
#     url(r'^user/$', views.MyItemsView.as_view(), name='user-items'),
#     url(r'^user/profile/$', views.ProfileView.as_view(), name='profile'),
#     url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),
# ]

urlpatterns = [
    url(r'^$', views.SectionListView.as_view(), name='index'),
    url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
    url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
    url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
    url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),
    url(r'^user/$', views.MyItemsView.as_view(), name='user-items'),
    url(r'^user/profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),
]



# urlpatterns += i18n_patterns(

#     )


#
# from django.urls import include, path
# from django.utils.translation import gettext_lazy as _
#
# urlpatterns += i18n_patterns(
#     path(_('new/'), never_cache(views.ItemCreateView.as_view()), name='item-new'),
# )

dcf/project/urls.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
app_name = "pinax_announcements"
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('django.contrib.auth.urls')),
]
urlpatterns += i18n_patterns(
	url(r'^', include('dcf.urls', namespace='dcf')),
	)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dcf/dcf/models.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.functional import cached_property
from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from sorl.thumbnail import ImageField
from unidecode import unidecode

from dcf import settings as dcf_settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(_('phone'), max_length=30, null=True, blank=True)
    receive_news = models.BooleanField(_('receive news'), default=True, db_index=True)

    def allow_add_item(self):
        return self.user.item_set.count() < dcf_settings.DCF_ITEM_PER_USER_LIMIT

    @staticmethod
    def get_or_create_for_user(user):
        if hasattr(user, 'profile'):
            return user.profile
        else:
            return Profile.objects.create(user=user)


@python_2_unicode_compatible
class Section(models.Model):
    title = models.CharField(_('title'), max_length=100)

    def __str__(self):
        return self.title

    @cached_property
    def count(self):
        return Item.objects \
            .filter(is_active=True) \
            .filter(group__section=self) \
            .count()

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')


@python_2_unicode_compatible
class Group(models.Model):
    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(_('title'), max_length=100)
    section = models.ForeignKey('Section', verbose_name=_('section'), on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' % (self.section.title, self.title)

    @cached_property
    def count(self):
        return self.item_set.filter(is_active=True).count()

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ['section__title', 'title', ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('dcf:group', kwargs={'pk': self.pk, 'slug': self.slug})


@python_2_unicode_compatible
class Item(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, verbose_name=_('group'), on_delete=models.CASCADE)

    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'))
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    is_active = models.BooleanField(_('display'), default=True, db_index=True)
    updated = models.DateTimeField(_('updated'), auto_now=True, db_index=True)
    posted = models.DateTimeField(_('posted'), auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('dcf:item', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def get_keywords(self):
        # TODO need more optimal keywords selection
        return ",".join(set(self.description.split()))

    @cached_property
    def image_count(self):
        return self.image_set.count()

    @cached_property
    def featured_image(self):
        return self.image_set.all().first()

    @cached_property
    def related_items(self):
        qs = Item.objects \
            .filter(is_active=True) \
            .filter(group=self.group) \
            .exclude(pk=self.pk)

        return qs[:dcf_settings.DCF_RELATED_LIMIT]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Item, self).save(*args, **kwargs)


class Image(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    file = ImageField(_('image'), upload_to='images')

dcf/dcf/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _

from dcf.models import Item, Group, Profile


class SearchForm(forms.Form):
    group = forms.ModelChoiceField(label=_('Group'), queryset=Group.objects.all(), required=False)
    q = forms.CharField(required=False, label=_('Query'),)

    def filter_by(self):
        # TODO search using more than one field
        # TODO split query string and make seaprate search by words
        filters = {}
        if self.cleaned_data['group']:
            filters['group'] = self.cleaned_data['group']
        filters['description__icontains'] = self.cleaned_data['q']

        return filters


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('group', 'title', 'description', 'price', 'is_active')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', )

dcf/dcf/views.py
# -*- coding:utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import reverse, reverse_lazy
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin

from dcf import settings as dcf_settings
from dcf.forms import ItemForm, ProfileForm, SearchForm
from dcf.models import Item, Image, Group, Section, Profile


class FilteredListView(FormMixin, ListView):
    def get_form_kwargs(self):
        return {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'data': self.request.GET or None
        }

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        form = self.get_form(self.get_form_class())

        if form.is_valid():
            self.object_list = self.object_list.filter(**form.filter_by())

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class SectionListView(ListView):
    model = Section


class SearchView(FilteredListView):
    form_class = SearchForm
    queryset = Item.objects.filter(is_active=True)
    paginate_by = 10
    template_name = 'dcf/search.html'


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        if hasattr(self, 'get_success_message'):
            self.get_success_message(form)
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class GroupDetail(SingleObjectMixin, ListView):
    paginate_by = dcf_settings.DCF_ITEM_PER_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Group.objects.all())
        return super(GroupDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupDetail, self).get_context_data(**kwargs)
        context['group'] = self.object
        return context

    def get_queryset(self):
        return self.object.item_set.all()


class ItemDetailView(DetailView):
    queryset = Item.objects.filter(is_active=True)


class ItemUpdateView(FormsetMixin, UpdateView):
    is_update_view = True
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, fields=('file',))

    def get_object(self, *args, **kwargs):
        obj = super(ItemUpdateView, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemUpdateView, self).dispatch(*args, **kwargs)


class ItemCreateView(FormsetMixin, CreateView):
    is_update_view = False
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, extra=3, fields=('file', ))

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        profile = Profile.get_or_create_for_user(self.request.user)
        if not profile.allow_add_item():
            messages.error(self.request, _('You have reached the limit!'))
            return redirect(reverse('dcf:user-items'))

        return super(ItemCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, formset):
        form.instance.user = self.request.user
        form.save()

        return super(ItemCreateView, self).form_valid(form, formset)


class MyItemsView(ListView):
    template_name = 'dcf/user_item_list.html'

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyItemsView, self).dispatch(*args, **kwargs)


class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('dcf:user-items')

    def get_queryset(self):
        qs = super(ItemDeleteView, self).get_queryset()

        if not self.request.user.is_superuser:
            qs = qs.filter(user=self.request.user)

        return qs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemDeleteView, self).dispatch(*args, **kwargs)


class ProfileView(UpdateView):
    template_name = 'dcf/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('dcf:profile')

    def get_object(self, queryset=None):
        return Profile.get_or_create_for_user(self.request.user)

    def form_valid(self, form):
        messages.success(self.request, _('Your profile settings was updated!'))
        return super(ProfileView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileView, self).dispatch(*args, **kwargs)


class RobotsView(TemplateView):
    template_name = 'dcf/robots.txt'
content_type = 'text/plain'

dcf/dcf/templates/dcf/_base.html
{% spaceless %}

  {% load staticfiles i18n %}

    <html lang="en">
    {% language request.session.lang %}
    <!DOCTYPE HTML>

    <head>
        <title>{% block title %}{% endblock title %} | {{ DCF_SITE_NAME }}</title>

        <meta name="description" content="{% block meta_description %}{{ DCF_SITE_DESCRIPTION }}{% endblock meta_description %}" />
        <meta name="keywords" content="{% block meta_keywords %}{% endblock meta_keywords %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% if GOOGLE_SITE_VERIFICATION_ID %}
            <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION_ID }}" />
        {% endif %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<!--       {% if FACEBOOK_APP_ID %}
        <meta property="fb:app_id" content="{{ FACEBOOK_APP_ID }}"/>
      {% endif %}
 -->      <meta property="og:type" content="website"/>
        {% block meta_og %}{% endblock %}

        <link rel="icon" type="image/x-icon" href="{% static 'dcf/img/favicon.ico' %}" />

      <link href="{% static 'dcf/css/bootstrap.min.css' %}" rel="stylesheet"/>
      <link href="{% static 'dcf/css/jumbotron-narrow.css' %}" rel="stylesheet"/>
        <link href="{% static 'dcf/css/lightbox.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'dcf/css/style.css' %}" rel="stylesheet" type="text/css"/>

      <link rel="alternate" type="application/rss+xml" href="{% url 'dcf:rss' %}">

    </head>

    <body>
    <div class="container">

        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                  {% if user.is_authenticated %}
                    <li role="presentation" class="active"><a href="{% url 'dcf:item-new' %}">{% trans "Add new" %}</a>
                    </li>
                  {% endif %}

                  <li role="presentation"><a href="{% url 'dcf:index' %}">{% trans "Home" %}</a></li>
                  <li role="presentation"><a href="{% url 'dcf:search' %}">{% trans "Search" %}</a></li>
                    {% if user.is_authenticated %}
                        <li role="presentation" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span> {{ user.get_full_name }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                              <li><a href="{% url 'dcf:user-items' %}">{% trans "My items" %} ({{ user.item_set.count }})</a>
                              </li>
                              <li>
                                <a href="{% url 'dcf:profile' %}">{% trans "Profile" %}</a>
                              </li>
                              <li class="divider"></li>
                              <li><a href="{% url 'logout' %}?next=/">{% trans "Logout" %}</a></li>
                            </ul>
                        </li>
                        {% endif %}

                </ul>
            </nav>
            <h3 class="text-muted">{{DCF_SITE_NAME}}</h3>
        </div>

        {% if messages %}
            {% for message in messages %}
                <div class='row'>
                    <div class="col-md-12">
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {{ message|safe }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}

        {% block body %}

        {% endblock %}

        <footer class="footer">
            <span class="pull-left">{{ DCF_SITE_NAME }}</span>
            {% if DCF_DISPLAY_CREDITS %}
                <span class="pull-right">{% trans "Powered by" %} <a href="https://github.com/inoks/dcf"
                                                                     title="DCF Django Classified App">DCF Django Classified App</a></span>
            {% endif %}
        </footer>

    </div>

    <script src="{% static 'dcf/js/jquery.min.js' %}"></script>
    <script src="{% static 'dcf/js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'dcf/js/lightbox.min.js' %}"></script>

    {% block ext_scripts%}{% endblock %}

    {% if GOOGLE_ANALYTICS_PROPERTY_ID %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
            ga('send', 'pageview');
        </script>
    {% endif %}

    <!-- generated {% now "jS F Y H:i:s" %} -->
    </body>
    </html>
    {% endlanguage %}
{% endspaceless %}

dcf/dcf/templates/dcf/admin_toolbar.inc.html
{% load i18n %}

{% if user.is_superuser %}
    <div class="row">
        <div class="col-lg-12">
          [<a href='{% url 'dcf:my-delete' item.pk %}'>{% trans "Delete" %}</a>]
          [<a href='{% url 'dcf:item-edit' item.pk %}'>{% trans "Edit" %}</a>]
        </div>
    </div>
{% endif %}

dcf/dcf/templates/dcf/form_pagination.inc.html
{% load i18n %}

<nav>
    <ul class="pagination">
        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_previous %}
                disabled="disabled"
                {% endif %}>
                {% trans "Prev" %}
            </button>
        </li>

        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_next %}
                disabled="disabled"
                {% endif %}>
               {% trans "Next" %}
            </button>
        </li>
    </ul>
</nav>

dcf/dcf/templates/dcf/item_confirm_delete.html
{% extends "dcf/_base.html" %}

{% load humanize thumbnail i18n %}

{% block title %}{% trans "Delete" %} {{ object.title }}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
          <form method="post">
                {% csrf_token %}
                <p>
                    {% trans "Are you sure you want to delete" %}
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a>?
                </p>
                <input type="submit" value="{% trans "Confirm" %}" class="btn btn-danger">
            </form>
        </div>
    </div>
{% endblock %}

dcf/dcf/templates/dcf/item_form.html
{% extends "dcf/_base.html" %}

{% load i18n bootstrap %}

{% block title %}{% if form.instance.pk %}{% trans "Edit" %}{% else %}{% trans "Add" %}{% endif %} {% trans "item" %}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <form enctype="multipart/form-data" method='post' role="form">
                {{ formset.management_form }}

                {% csrf_token %}

                {{ form|bootstrap }}

                {% for form in formset %}
                    {{ form|bootstrap }}
                {% endfor %}
                <input type='submit' class="btn" value='{% trans "Save" %}'>
            </form>
        </div>
    </div>
{% endblock body %}

dcf/dcf/templates/dcf/item_list.inc.html
{% load humanize thumbnail i18n%}

{% for object in object_list %}
    {% if forloop.first  %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <td></td>
                    <td>{% trans "Price" %}</td>
                </tr>
            </thead>
            <tbody>
    {%  endif %}
                <tr>
                    <td>
                      {% if object.featured_image %}
                        {% thumbnail object.featured_image.file "45x45" crop="center" as im %}
                          <a href='{{ object.get_absolute_url }}' title="{{ object.title }}">
                            <img
                                    src='{{ im.url }}'
                                    alt='{{ object.title }}'
                                    title='{{ object.title }}'
                                    width="{{ im.width }}"
                                    height="{{ im.height }}"
                                    class="img-rounded"
                            />
                            {% if object.image_count > 1 %}
                              <span class="badge badge-notify"
                                    title="{{ object.image_count|add:-1 }} {% trans 'more photos available' %}"> + {{ object.image_count|add:-1 }}</span>
                                    {% endif %}
                                </a>
                            {% endthumbnail %}
                        {% endif %}
                      <a href='{{ object.get_absolute_url }}' title='{{ object.title }}'>
                        {{ object.title }}
                        </a>
                    </td>
                    <td>
                        {{ object.price|default:"" }}
                    </td>
                </tr>
{% if forloop.last %}
        </tbody>
    </table>
{% endif %}

{% empty %}
    <p>
        {% trans "No item here yet." %}
      <a href="{% url 'dcf:item-new' %}">{% trans "Add one now!" %}</a>
    </p>
{% endfor %}

dcf/dcf/templates/dcf/search.html
{% extends "dcf/_base.html" %}

{% load i18n bootstrap %}

{% block title %}
    {% if form.q.value  %}{% trans "Search results for query" %} "{{ form.q.value }}" {% else %}{% trans "Search" %}{% endif %}
{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-6">
            <h3>{% trans "Search" %}</h3>
            <form method="get" role="form">
                {{ form|bootstrap }}
                <button type="submit" class="btn" name="page" value="1">{% trans "Search" %}</button>
                {% if object_list|length %}
                    {% include 'dcf/form_pagination.inc.html' %}
                {% endif %}
            </form>
        </div>
    </div>
    <div>
        <hr/>
        {% if object_list|length %}
            <h4>{% blocktrans %}Search results ({{ paginator.count }} items found):{% endblocktrans %}</h4>
            {% include "dcf/item_list.inc.html" with item=object %}
        {% else %}
            <h4>{% trans "Not found" %}</h4>
        {% endif %}
    </div>
{% endblock %}

dcf/dcf/templates/dcf/section_list.html
{% extends "dcf/_base.html" %}

{% block title %}{{ DCF_SITE_NAME }}{% endblock title %}

{% block body %}
    {% for object in object_list %}
        {% if forloop.first %}
            <div class="row marketing">
        {% endif %}

        <div class="col-lg-4">
          <h4>{{ object }} [{{ object.count }}]</h4>

            {% for group in object.group_set.all %}
                {% if group.count > 0 %}
                  <a href='{{ group.get_absolute_url }}' title="{{ group.title }}">
                    {{ group.title }} [{{ group.count }}]<br/>
                    </a>
                {% endif %}
            {% endfor %}
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
            </div>
            {% if not forloop.last %}
                <div class="row marketing">
            {% endif %}
        {% endif %}
    {% endfor %}
{% endblock %}

dcf/dcf/templates/dcf/user_item_list.html
{% extends "dcf/_base.html" %}

{% load humanize i18n %}

{% block title %}{%  trans "My items" %}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2>{%  trans "My items" %}</h2>
            {% for object in object_list %}
                {% if forloop.first  %}
                    <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <td>{%  trans "Group" %}</td>
                        <td>{%  trans "Update" %}</td>
                        <td>{%  trans "Link" %}</td>
                        <td>{%  trans "Price" %}</td>
                        <td>{%  trans "Posted" %}</td>
                        <td>{%  trans "Delete" %}</td>
                    </tr>
                    </thead>
                {%  endif %}
            <tr>
                <td><a href='{{ object.group.get_absolute_url }}'>{{object.group}}</a></td>
              <td><a href='{% url 'dcf:item-edit' object.pk %}' title='{% trans "Edit item" %}'>{{ object.title }}</a>
              </td>
              <td><a href='{{ object.get_absolute_url }}' title='{% trans "Open item" %}'>{% trans "Open" %}</a></td>
                <td>{{object.price|intcomma}}</td>
                <td>{{object.posted|date:"d.m.Y"}}</td>
              <td><a href='{% url 'dcf:my-delete' object.id %}'>{% trans "Delete" %}</a></td>
            </tr>

            {% if forloop.last  %}
                </table>
            {% endif %}

            {% empty %}
                <p>
                    {%  trans "You have no items to show." %}
                  <a href="{% url 'dcf:item-new' %}">{% trans "Add one now!" %}</a>
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}